

@startuml

hide footbox

participant "Client B\n(LRM)" as LRM
participant "Hub Santé\n" as Hub
participant "Client A\n(PTF SAS)" as PTF

PTF -> Hub : 1. Envoi du message fonctionnel
Hub --> PTF : 2. Acquittement technique
Hub -> Hub : 2.1 Inscription dans la file B.message
Hub -> LRM : 3. Transmission du message \nau destinataire
LRM -> Hub : 4. Acquittement final
Hub -> Hub : 4.1 Inscription dans la file A.ack
Hub -> PTF : 4.2 Tranmission de l'acquittement \nau destinataire
LRM -> Hub : 5. Message d'erreur \n(si applicable)
Hub -> Hub : 5.1 Inscription dans la file A.info
Hub -> PTF : 5.2 Tranmission du message d'erreur \nau destinataire

@enduml