@startuml
"Plateforme SAS" --> "Solution interfacée": Requête **<color:blue>PUT Practitioner?identifier=[ID]</color>**
"Solution interfacée" -> "Plateforme SAS": Réponse **<color:blue>200 OK</color>**
@enduml