@startuml
"Solution interfacée" --> "Plateforme SAS": Requête **<color:blue>PUT Appointment?Identifier=[ID]</color>**
"Plateforme SAS" -> "Solution interfacée": Réponse **<color:blue>200 OK</color>**
@enduml