@startuml
"Plateforme SAS" -> "Solution interfacée": Requête disponibilités **<color:blue>GET Slot</color>**
"Solution interfacée" --> "Plateforme SAS": Réponse disponibilités **<color:blue>200 OK Bundle Searchset</color>**
@enduml