# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.sas
canonical: https://interop.esante.gouv.fr/ig/fhir/sas
name: Service d'Accès aux Soins
title: Service d'Accès aux Soins
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

dependencies:
  hl7.fhir.fr.core: 1.1.0

pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles_1.md:
        title: PS à titre individuel
    specifications_fonctionnelles_2.md:
        title: CPTS
    specifications_techniques_1_1.md:
        title: Recherche des créneaux
    specifications_techniques_1_2.md:
        title: Création de rendez-vous
    specifications_techniques_1_3.md:
        title: Mise à jour de rendez-vous
    specifications_techniques_2_1.md:
        title: Recherche des créneaux
    specifications_techniques_2_2.md:
        title: Création de rendez-vous
    specifications_techniques_2_3.md:
        title: Mise à jour de rendez-vous
    ressources.md:
        title: Ressources de conformité
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        faq.md:
            title: FAQ
        annexes.md:
            title: Annexes
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Spécifications fonctionnelles: 
        PS à titre individuel: specifications_fonctionnelles_1.html
        CPTS: specifications_fonctionnelles_2.html
    Spécifications techniques: 
        PS à titre individuel: 
            Recherche des créneaux: specifications_techniques_1_1.html
            Création de rendez-vous: specifications_techniques_1_2.html
            Mise à jour de rendez-vous: specifications_techniques_1_3.html
        CPTS:
            Recherche des créneaux: specifications_techniques_2_1.html
            Création de rendez-vous: specifications_techniques_2_2.html
            Mise à jour de rendez-vous: specifications_techniques_2_3.html
    Ressources de conformité: ressources.html
    Autres ressources:
        Sécurité: securite.html
        FAQ: faq.html
        Annexes: annexes.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
