# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.sas
canonical: https://interop.esante.gouv.fr/ig/fhir/sas
name: SAS
title: Service d'Accès aux Soins
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: active
version: 1.0.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

dependencies:
    hl7.fhir.fr.core: 1.1.0
    hl7.fhir.extensions.r5: 4.0.1
    ans.fr.nos: 1.3.0

pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles.md:
        title: Spécif. fonctionnelles
    specifications_techniques-ps-recherche_creneaux.md:
        title: PS indiv. - Recherche des créneaux
    specifications_techniques-ps-gestion_rdv.md:
        title: PS indiv. - Gestion de rendez-vous
    specifications_techniques-cpts-recherche_creneaux.md:
        title: CPTS - Recherche des créneaux
    specifications_techniques-cpts-gestion_rdv.md:
        title: CPTS - Gestion de rendez-vous
    specifications_techniques-sos-recherche_creneaux.md:
        title: SOS Médecins - Recherche des créneaux   
    specifications_techniques-sos-gestion_rdv.md:
        title: SOS Médecins - Gestion de rendez-vous      
    ressources_casusage.md:
        title: Ressources par cas d'usage
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        faq.md:
            title: FAQ
        annexes.md:
            title: Annexes
        downloads.md:
            title: Téléchargements et usages

menu:
    Accueil: index.html
    Spécif. fonctionnelles: specifications_fonctionnelles.html
    Spécif. techniques: 
        ________ PS indiv. ________:
        PS indiv. - Recherche des créneaux: specifications_techniques-ps-recherche_creneaux.html
        PS indiv. - Gestion de rendez-vous: specifications_techniques-ps-gestion_rdv.html
        _________ CPTS _________:
        CPTS - Recherche des créneaux: specifications_techniques-cpts-recherche_creneaux.html
        CPTS - Gestion de rendez-vous: specifications_techniques-cpts-gestion_rdv.html
        ________ SOS Médecins ________:
        SOS Médecins - Recherche des créneaux: specifications_techniques-sos-recherche_creneaux.html
        SOS Médecins - Gestion de rendez-vous: specifications_techniques-sos-gestion_rdv.html
    Ressources par cas d'usage: ressources_casusage.html 
    Ressources de conformité: artifacts.html
    Autres ressources:
        Sécurité: securite.html
        FAQ: faq.html
        Annexes: annexes.html
        Téléchargements et usage: downloads.html
        Spécifications FHIR: new-tab {{site.data.fhir.path}}index.html
        Site de l'ANS: new-tab https://esante.gouv.fr/
    Documentation: new-tab https://interop.esante.gouv.fr/ig/documentation/
