# Documentation à propos de cette page : https://fshschool.org/docs/sushi/configuration/

id: ans.fhir.fr.sas
canonical: https://interop.esante.gouv.fr/ig/fhir/sas
name: Service d'Accès aux Soins
title: Service d'Accès aux Soins
publisher:
  name: ANS
  url: https://esante.gouv.fr
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2020+
releaseLabel: ci-build
jurisdiction: urn:iso:std:iso:3166#FR "FRANCE"

parameters:
    shownav: 'true'

dependencies:
  hl7.fhir.fr.core: 1.1.0

pages:
    index.md:
        title: Accueil
    specifications_fonctionnelles-ps.md:
        title: PS à titre individuel
    specifications_fonctionnelles-cpts.md:
        title: CPTS
    specifications_techniques-ps-recherche_creneaux.md:
        title: PS - Recherche des créneaux
    specifications_techniques-ps-creation_rdv.md:
        title: PS - Création de rendez-vous
    specifications_techniques-ps-maj_rdv.md:
        title: PS - Mise à jour de rendez-vous
    specifications_techniques-cpts-recherche_creneaux.md:
        title: CPTS - Recherche des créneaux
    specifications_techniques-cpts-creation_rdv.md:
        title: CPTS - Création de rendez-vous
    specifications_techniques-cpts-maj_rdv.md:
        title: CPTS - Mise à jour de rendez-vous
    ressources.md:
        title: Ressources de conformité
    autres_ressources.md:
        title: Autres Ressources
        securite.md:
            title: Sécurité
        faq.md:
            title: FAQ
        annexes.md:
            title: Annexes
        downloads.md:
            title: Téléchargements et usages
    about.md:
        title: A propos de ce guide

menu:
    Accueil: index.html
    Spécifications fonctionnelles: 
        PS à titre individuel: specifications_fonctionnelles-ps.html
        CPTS: specifications_fonctionnelles-cpts.html
    Spécifications techniques: 
        PS - Recherche des créneaux: specifications_techniques-ps-recherche_creneaux.html
        PS - Création de rendez-vous: specifications_techniques-ps-creation_rdv.html
        PS - Mise à jour de rendez-vous: specifications_techniques-ps-maj_rdv.html
        CPTS - Recherche des créneaux: specifications_techniques-cpts-recherche_creneaux.html
        CPTS - Création de rendez-vous: specifications_techniques-cpts-creation_rdv.html
        CPTS - Mise à jour de rendez-vous: specifications_techniques-cpts-maj_rdv.html
    Ressources de conformité: ressources.html
    Autres ressources:
        Sécurité: securite.html
        FAQ: faq.html
        Annexes: annexes.html
        Téléchargements et usage: downloads.html
        "Spécifications FHIR ": new-tab {{site.data.fhir.path}}index.html
        "Site de l'ANS ": new-tab https://esante.gouv.fr/
    A propos de ce guide: about.html
