name: Workflow Release to IG-website-release
on:
  workflow_call:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:      
          path: igSource

      - name: Copy "all" to "use cases" specs
        run: |
             path_spec="./igSource/input/pagecontent"
             for lines in $(cat "${path_spec}/specifications_techniques.txt"); do
               files=(${lines//;/ })
               cp "${path_spec}/${files[0]}" "${path_spec}/${files[1]}"
             done
         
      - uses: ansforge/IG-workflows@main
        with:      
          repo_ig: "./igSource"   
          github_page: "true"
          github_page_token: ${{ secrets.GITHUB_TOKEN }}
          bake: "true"
          nos: "false"
          validator_cli: "false"
          publish_repo: "ansforge/IG-website-release"
          publish_repo_token :  ${{ secrets.ANS_IG_API_TOKEN }} 
          publish_path_outpout : "./IG-website-release/www/ig/fhir"
