name: Workflow   Tests/gitHubpages
on:
  workflow_call:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run-gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:      
          path: igSource

      - name: Copy "all" to "use cases" specs
        run: |
          cp "./igSource/input/pagecontent/specifications_techniques-tous-creation_rdv.md" "./igSource/input/pagecontent/specifications_techniques-ps-creation_rdv.md"
          cp "./igSource/input/pagecontent/specifications_techniques-tous-creation_rdv.md" "./igSource/input/pagecontent/specifications_techniques-cpts-creation_rdv.md"
          cp "./igSource/input/pagecontent/specifications_techniques-tous-maj_rdv.md" "./igSource/input/pagecontent/specifications_techniques-ps-maj_rdv.md"
          cp "./igSource/input/pagecontent/specifications_techniques-tous-maj_rdv.md" "./igSource/input/pagecontent/specifications_techniques-cpts-maj_rdv.md"

      - uses: ansforge/IG-workflows@v0.2.0
        with:      
          bake: "true"
          nos: "true"
          validator_cli: "true"     
          generate_plantuml : "true"
          repo_ig: "./igSource"   
          github_page: "true"
          github_page_token: ${{ secrets.ANS_IG_API_TOKEN  }}
