name: Workflow   Tests/gitHubpages
on:
  workflow_call:
  push:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  run-gitHubPages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:      
          path: igSource

      - name: Copy "all" to "use cases" specs
        run: |
             path_spec="./igSource/input/pagecontent"
             for lines in $(cat "${path_spec}/specifications_techniques.txt"); do
               files=(${lines//;/ })
               cp "${path_spec}/${files[0]}" "${path_spec}/${files[1]}"
             done

      - uses: ansforge/IG-workflows@main
        with:      
          bake: "true"
          nos: "false"
          validator_cli: "true"     
          generate_plantuml : "true"
          repo_ig: "./igSource"   
          github_page: "true"
          github_page_token: ${{ secrets.ANS_IG_API_TOKEN  }}
          ig-publisher-version: 1.6.20
